[build]
  publish = "."

[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
